version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simpletasks_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - simpletasks

  nginx:
    image: nginx:latest
    container_name: simpletasks_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - simpletasks
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: simpletasks_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: simpletasks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - simpletasks

networks:
  simpletasks:

volumes:
  db_data:
